#!/bin/bash
exec 2>&1
PODNAME=$(<./env/PODNAME)
WORKDIR=$(<./env/WORKDIR)
if ! podman pod exists "$PODNAME"
then
    echo "Pod $PODNAME does not exist, creating it"
    podman pod create --name "$PODNAME" -p 18080:3000 -p 18081:8443
fi
exec podman run --pod "$PODNAME" -v "$WORKDIR"/nodetube:/app -v /app/node_modules -v "$WORKDIR"/upload:/app/upload -v "$WORKDIR"/uploads:/app/uploads -e REDIS_HOST=localhost -e MONGODB_DOCKER_URI=mongodb://localhost:27017/nodetube --rm -it localhost/nodetube-bougyman npm start
