#!/bin/bash
exec 2>&1
set -x
PODNAME=$(<./env/PODNAME)
WORKDIR=$(<./env/WORKDIR)
if ! podman pod exists "$PODNAME"
then
    echo "Pod $PODNAME does not exist, sleeping for a bit"
    exec sleep 5
fi
exec podman run --pod "$PODNAME" -v "$WORKDIR"/data/db:/data/db mongo:3.6
